# Generated by Django 5.2.7 on 2025-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du service')),
                ('description', models.TextField(verbose_name='Description du service')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (en GNF)')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails ou sous-services')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_creation'],
            },
        ),
    ]
