# Generated by Django 5.2.7 on 2025-10-25 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='Date_creation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Prix',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Titre',
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Détails ou sous-services'),
        ),
        migrations.AddField(
            model_name='service',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Description du service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (en GNF)'),
        ),
        migrations.AddField(
            model_name='service',
            name='titre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Titre du service'),
            preserve_default=False,
        ),
    ]
